import { withBase } from "@/lib/withBase";
/** Aperture Blue about page: studio character shown through a composed visual sequence and usable contact desk. */
import { useState } from "react";
import { ArrowUpRight, CheckCircle2, Mail, MapPin } from "lucide-react";
import { SiteShell } from "@/components/SiteShell";
const studioUrl = withBase("/images/halcyon-portrait-studio_f4f46fb1.jpg");
export default function About() {
  const [sent, setSent] = useState(false);
  return <SiteShell><main><section className="px-5 pb-12 pt-16 md:px-9 md:pb-20 md:pt-24"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[1fr_1fr] lg:items-end"><div className="frame-rule"><p className="eyebrow text-[#2783a8]">Frame / about Halcyon</p><h1 className="mt-3 max-w-2xl text-5xl font-extrabold leading-[.92] tracking-[-.085em] md:text-7xl">Images that know when not to interrupt.</h1></div><p className="max-w-xl text-lg leading-8 text-[#142128]/68">Halcyon is a small photography studio with a low-pressure way of working: prepared enough to be useful, alert enough to catch what cannot be planned.</p></div></section>
    <section className="px-5 pb-20 md:px-9 md:pb-28"><div className="mx-auto grid max-w-[1440px] gap-0 lg:grid-cols-12"><img src={studioUrl} alt="Natural-light studio portrait session" className="h-[540px] w-full object-cover lg:col-span-6" /><div className="frame-stack bg-[#f1f7f8] p-7 md:p-10 lg:col-span-6 lg:mt-20"><span className="aperture-tab" /><p className="eyebrow mt-5 text-[#2783a8]">Our point of view / 02</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.06em] md:text-4xl">The best photographs make more room for your memory, not ours.</h2><div className="mt-10 grid gap-6 sm:grid-cols-2"><div><p className="text-sm font-extrabold">A calm set</p><p className="mt-2 text-sm leading-6 text-[#142128]/64">Clear direction when you want it, space when you don’t. No manufactured urgency.</p></div><div><p className="text-sm font-extrabold">A useful plan</p><p className="mt-2 text-sm leading-6 text-[#142128]/64">You will know the timing, the coverage, and the next step before you commit.</p></div></div></div></div></section>
    <section className="bg-white px-5 py-16 md:px-9 md:py-20"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[.82fr_1.18fr]"><div className="frame-rule"><p className="eyebrow text-[#2783a8]">Desk / contact</p><h2 className="mt-3 text-4xl font-extrabold leading-[.97] tracking-[-.065em]">Tell us what you’re making space for.</h2><div className="mt-8 space-y-4 text-sm text-[#142128]/68"><p className="flex items-center gap-3"><Mail size={16} className="text-[#2783a8]" /> hello@halcyon.photo</p><p className="flex items-center gap-3"><MapPin size={16} className="text-[#2783a8]" /> Serving the city + nearby coast</p></div></div><form onSubmit={(event) => { event.preventDefault(); setSent(true); }} className="call-sheet p-6 md:p-8">{sent ? <div className="grid min-h-[300px] place-items-center text-center"><div><CheckCircle2 size={36} className="mx-auto text-[#2783a8]" /><h3 className="mt-4 text-2xl font-extrabold tracking-[-.05em]">Your note is safely on its way.</h3><p className="mt-2 max-w-sm text-sm leading-6 text-[#142128]/62">This demo form has saved the interaction locally. In a production setup, it would send directly to the studio desk.</p></div></div> : <><div className="grid gap-4 sm:grid-cols-2"><label className="field-label">Your name<input required placeholder="Jordan Lee" className="field-input" /></label><label className="field-label">Email<input required type="email" placeholder="you@example.com" className="field-input" /></label></div><label className="field-label mt-4">What are you considering?<textarea required rows={5} placeholder="A small wedding, a new chapter, a reason to get everyone together..." className="field-input resize-none" /></label><button className="button-primary mt-6">Send a considered note <ArrowUpRight size={15} /></button></>}</form></div></section>
  </main></SiteShell>;
}
