/** Aperture Blue home: a contact-sheet sequence of image spills, frame codes, and composed calls to action. */
import { ArrowDownRight, ArrowUpRight, CalendarDays, Image, Sun } from "lucide-react";
import { Link } from "wouter";
import { SiteShell } from "@/components/SiteShell";

const heroUrl = "/images/halcyon-hero-outdoor-wedding_5c6c1a70.jpg";
const portraitUrl = "/images/halcyon-portrait-studio_f4f46fb1.jpg";
const editorialUrl = "/images/halcyon-editorial-on-location_d3fc4a67.jpg";

export default function Home() {
  return <SiteShell><main>
    <section className="relative isolate min-h-[680px] overflow-hidden bg-[#142128] md:min-h-[760px]"><img src={heroUrl} alt="A newly married couple walking through coastal grass at blue hour" className="absolute inset-0 h-full w-full object-cover object-[66%_center]" /><div className="absolute inset-0 bg-gradient-to-r from-[#102129]/88 via-[#102129]/38 to-transparent" /><div className="relative mx-auto flex min-h-[680px] max-w-[1440px] flex-col justify-end px-5 pb-12 pt-32 text-white md:min-h-[760px] md:px-9 md:pb-20"><div className="max-w-3xl animate-frame-in"><div className="flex items-center gap-3"><span className="aperture-tab" /><p className="eyebrow text-[#b9e3ef]">Frame 01 · portrait · editorial · wedding day</p></div><h1 className="mt-5 max-w-2xl text-5xl font-extrabold leading-[.92] tracking-[-.085em] md:text-7xl lg:text-8xl">The moments that stay in motion.</h1><p className="mt-6 max-w-lg text-base leading-7 text-white/78 md:text-lg">Thoughtful photography for the people and days that resist being put in a box. We’ll make room for the real part.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/book" className="button-light">Check availability <ArrowUpRight size={16} /></Link><Link href="/services" className="button-ghost-light">Explore coverage <ArrowDownRight size={16} /></Link></div></div></div><div className="absolute bottom-0 right-0 hidden w-[250px] border-l border-t border-white/15 bg-[#142128]/72 p-5 text-xs leading-5 text-white/67 backdrop-blur-md md:block"><span className="eyebrow text-[#9ed6e9]">Exposure note / 001</span><p className="mt-2 font-semibold text-white">Wind, open sky, and the part after everyone exhales.</p></div></section>
    <section className="px-5 py-20 md:px-9 md:py-28"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.7fr_1.3fr] lg:gap-20"><div className="frame-rule"><p className="eyebrow text-[#2783a8]">Studio note / 002</p><h2 className="mt-3 max-w-sm text-4xl font-extrabold leading-[.98] tracking-[-.065em] md:text-5xl">You don’t need to know what to do with your hands.</h2></div><div className="grid gap-7 sm:grid-cols-2"><p className="text-lg leading-8 text-[#142128]/70">Halcyon is for the people who want images with an afterlife: images that feel like a place you can return to, not a performance you had to get through.</p><div className="frame-rule"><p className="text-sm font-extrabold">Clear before creative.</p><p className="mt-2 text-sm leading-6 text-[#142128]/61">A helpful intake, visible availability, and a plain-language hold make the planning feel as calm as the photographs.</p></div></div></div></section>
    <section className="relative overflow-hidden bg-white px-5 py-8 md:px-9 md:py-12"><div className="mx-auto grid max-w-[1440px] gap-4 md:grid-cols-12 md:gap-8"><div className="relative min-h-[560px] overflow-hidden md:col-span-7"><img src={portraitUrl} alt="Editorial studio portrait in a porcelain-white photo studio" className="h-full w-full object-cover" /><div className="absolute bottom-0 left-0 bg-[#f4f7f8]/93 p-5 backdrop-blur-md"><p className="eyebrow text-[#2783a8]">Frame 03 / The whole story</p><p className="mt-1 text-sm font-extrabold">A session with room to settle in</p></div></div><div className="flex flex-col gap-4 md:col-span-5 md:pt-20"><div className="relative min-h-[290px] overflow-hidden"><img src={editorialUrl} alt="Friends photographed beneath coastal city concrete architecture" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#142128]/60 to-transparent" /><p className="absolute bottom-5 left-5 max-w-[230px] text-lg font-extrabold leading-6 tracking-[-.035em] text-white">A little direction. A lot of room to become yourself.</p></div><Link href="/services" className="group frame-stack flex min-h-[190px] flex-1 flex-col justify-between bg-[#f4f7f8] p-7 text-[#142128] transition-colors hover:bg-[#edf6f8]"><span className="grid h-10 w-10 place-items-center rounded-full border border-[#50a6c6] text-[#2783a8] transition-transform group-hover:rotate-[-14deg]"><ArrowUpRight size={19} /></span><div><p className="eyebrow text-[#2783a8]">Index / The work</p><h3 className="mt-2 text-3xl font-extrabold tracking-[-.06em]">Find the right kind of coverage.</h3></div></Link></div></div></section>
    <section className="px-5 py-20 md:px-9 md:py-28"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div className="frame-rule"><p className="eyebrow text-[#2783a8]">Contact sheet / 004–006</p><h2 className="mt-3 text-4xl font-extrabold tracking-[-.065em] md:text-5xl">The practical parts, made gentle.</h2></div><Link href="/book" className="text-sm font-bold text-[#2783a8] underline underline-offset-4">Try the booking desk</Link></div><div className="mt-10 border-y border-[#142128]/12">{[{ icon: CalendarDays, num: "04", title: "Start with a few signals", body: "Tell us how you want the session to feel. We’ll carry those answers forward, not make you repeat them." }, { icon: Sun, num: "05", title: "Choose time with the light", body: "Outdoor coverage is offered inside the actual golden-hour window for the season, while studio days stay flexible." }, { icon: Image, num: "06", title: "Keep your images close", body: "Private delivery gives you a clear count, an arrival time, and optional printed pieces when the edit is ready." }].map((item, index) => <article key={item.num} className={`grid gap-5 border-b border-[#142128]/12 py-7 last:border-b-0 md:grid-cols-[70px_1fr_1.15fr] md:items-start ${index === 1 ? "md:ml-[8%]" : ""}`}><div className="flex items-center gap-3"><span className="aperture-tab h-2 w-4" /><span className="font-mono text-[11px] font-bold text-[#142128]/42">{item.num}</span></div><h3 className="text-xl font-extrabold tracking-[-.04em]"><item.icon size={18} className="mr-2 inline text-[#2783a8]" />{item.title}</h3><p className="text-sm leading-6 text-[#142128]/62">{item.body}</p></article>)}</div></div></section>
    <section className="relative overflow-hidden bg-white px-5 py-16 md:px-9 md:py-20"><div className="absolute bottom-0 right-0 top-0 w-[34%] bg-[#e5f2f6]" /><div className="relative mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div className="frame-rule"><p className="eyebrow text-[#2783a8]">Availability / 007</p><h2 className="mt-3 max-w-3xl text-4xl font-extrabold leading-[.95] tracking-[-.07em] md:text-6xl">Some things are worth putting on the calendar.</h2></div><div><p className="max-w-sm text-base leading-7 text-[#142128]/72">See what fits, see what’s available, and put the date on hold while you read the fine print.</p><Link href="/book" className="button-dark mt-6">Start a session request <ArrowUpRight size={16} /></Link></div></div></section>
  </main></SiteShell>;
}
