import { withBase } from "@/lib/withBase";
/** Aperture Blue services: coverage is sequenced like a contact sheet, with facts replacing dashboard chrome. */
import { ArrowUpRight, Check } from "lucide-react";
import { Link } from "wouter";
import { SiteShell } from "@/components/SiteShell";
import { formatPrice, packages } from "@/data/photography";
const editorialUrl = withBase("/images/halcyon-editorial-on-location_d3fc4a67.jpg");

export default function Services() {
  return <SiteShell><main><section className="px-5 pb-12 pt-16 md:px-9 md:pb-20 md:pt-24"><div className="mx-auto max-w-[1440px]"><div className="frame-rule"><p className="eyebrow text-[#2783a8]">Index / services + pricing</p><div className="mt-3 grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><h1 className="max-w-3xl text-5xl font-extrabold leading-[.92] tracking-[-.085em] md:text-7xl">Coverage with a reason for every minute.</h1><p className="self-end max-w-md text-base leading-7 text-[#142128]/66">Start with the type of experience you want, then see exactly what it includes. A retainer places the date on the calendar; no surprises before that.</p></div></div></div></section>
    <section className="px-5 pb-20 md:px-9 md:pb-28"><div className="mx-auto grid max-w-[1440px] gap-x-6 gap-y-0 border-y border-[#142128]/14 md:grid-cols-12">{packages.map((item, index) => <article key={item.id} className={`group relative flex min-h-[365px] flex-col justify-between border-b border-[#142128]/14 p-6 last:border-b-0 md:p-8 ${index === 0 ? "md:col-span-7 md:border-r" : index === 1 ? "md:col-span-5 md:mt-16" : index === 2 ? "md:col-span-5 md:border-r" : "md:col-span-7 md:mt-16"}`}><span className="absolute left-0 top-8 h-7 w-1 bg-[#50a6c6]" /><div className="flex justify-between gap-5"><div><p className="eyebrow text-[#2783a8]">0{index + 1} / {item.locationLabel}</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.06em] md:text-4xl">{item.name}</h2><p className="mt-2 text-sm font-semibold text-[#142128]/60">{item.bestFor}</p></div><div className="text-right"><p className="font-mono text-[11px] font-bold text-[#142128]/45">FROM</p><p className="mt-1 text-xl font-extrabold tracking-[-.045em]">{formatPrice(item.price)}</p></div></div><div className="mt-10 grid gap-7 sm:grid-cols-[1fr_auto] sm:items-end"><ul className="space-y-2.5">{item.includes.map((detail) => <li key={detail} className="flex items-center gap-2 text-xs font-semibold text-[#142128]/70"><Check size={14} className="text-[#2783a8]" />{detail}</li>)}</ul><Link href={`/book?package=${item.id}`} className="button-dark w-fit">Select coverage <ArrowUpRight size={15} /></Link></div></article>)}</div></section>
    <section className="relative overflow-hidden bg-[#142128] px-5 py-10 text-white md:px-9 md:py-14"><div className="absolute bottom-0 left-[42%] top-0 hidden w-px bg-[#50a6c6]/55 md:block" /><div className="relative mx-auto grid max-w-[1440px] gap-10 md:grid-cols-[.8fr_1.2fr] md:items-center"><div className="frame-rule border-[#50a6c6]"><p className="eyebrow text-[#9ed6e9]">Light table / outdoor timing</p><h2 className="mt-3 text-4xl font-extrabold leading-[.95] tracking-[-.06em]">June and December should never look like the same appointment.</h2><p className="mt-5 max-w-md text-sm leading-6 text-white/65">Outdoor session times follow a seeded sunset table, so the booking desk only opens slots inside each day’s available golden-hour light. Studio sessions remain open in daylight business hours.</p></div><img src={editorialUrl} alt="On-location editorial portraits in soft daylight" className="h-[360px] w-full object-cover md:ml-10 md:w-[calc(100%-2.5rem)]" /></div></section>
  </main></SiteShell>;
}
